- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    echo "Installing dependencies..."
    pip install -r requirements.txt
    echo "Dependencies installed."

- name: Run Python script
  run: |
    echo "Running Python script..."
    python app.py
    echo "Python script completed."
